# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: My Documentation
site_url: https://elfua.github.io/natto/
repo_url: https://github.com/elfua/natto.git
repo_name: natto

theme:
  name: material
  language: es
  palette: 
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Night
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Day
  features:
    - navigation.tabs          # Top-level tabs
    - navigation.sections      # Grouped sidebar items
    - navigation.top           # "Back to top" button
    - navigation.tracking      # Update URL as you scroll
    - content.code.copy        # "Copy to clipboard" button for code blocks
    - search.suggest           # Search suggestions
    - search.highlight         # Highlight search terms on page

markdown_extensions:
  - admonition                 # Info, Warning, Danger blocks
  - pymdownx.details           # Collapsible blocks
  - pymdownx.superfences       # Nested code blocks
  - pymdownx.highlight:        # Syntax highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite      # Inline code highlighting
  - pymdownx.tabbed:           # Tabbed content blocks
      alternate_style: true
  - toc:
      permalink: true          # Adds anchor links to headers

plugins:
  - search